// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8v_ku0tZ2b7fqy9EqGdEmWXXwTaUszM',
    appId: '1:204477371678:web:191c5aa36e21f82c53250f',
    messagingSenderId: '204477371678',
    projectId: 'tp3firebase-b604d',
    authDomain: 'tp3firebase-b604d.firebaseapp.com',
    storageBucket: 'tp3firebase-b604d.firebasestorage.app',
    measurementId: 'G-WCMC9DS44W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7fpiIqUL8qHDVwz3B7oqVXcQTc2VDRs',
    appId: '1:204477371678:android:55c1c1debb15655c53250f',
    messagingSenderId: '204477371678',
    projectId: 'tp3firebase-b604d',
    storageBucket: 'tp3firebase-b604d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWIA5-kh9CIvrnQi1MzlVWFhvqs0rFTRw',
    appId: '1:204477371678:ios:0a1e5ea2cf2cc8ea53250f',
    messagingSenderId: '204477371678',
    projectId: 'tp3firebase-b604d',
    storageBucket: 'tp3firebase-b604d.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWIA5-kh9CIvrnQi1MzlVWFhvqs0rFTRw',
    appId: '1:204477371678:ios:0a1e5ea2cf2cc8ea53250f',
    messagingSenderId: '204477371678',
    projectId: 'tp3firebase-b604d',
    storageBucket: 'tp3firebase-b604d.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO8v_ku0tZ2b7fqy9EqGdEmWXXwTaUszM',
    appId: '1:204477371678:web:f5ed120b0dc4200353250f',
    messagingSenderId: '204477371678',
    projectId: 'tp3firebase-b604d',
    authDomain: 'tp3firebase-b604d.firebaseapp.com',
    storageBucket: 'tp3firebase-b604d.firebasestorage.app',
    measurementId: 'G-BHRZ5E9VHK',
  );
}
